
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILURE = "ADD_PRODUCT_TO_CART_FAILURE";

export const GET_ALL_CART = "GET_ALL_CART";
export const GET_ALL_CART_SUCCESS = "GET_ALL_CART_SUCCESS";
export const GET_ALL_CART_FAILURE = "GET_ALL_CART_FAILURE";


export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";

export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";

